language: ruby
rvm:
  - 2.3
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_edge.gemfile

jobs:
  exclude:
  - rvm: 2.3
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.3
    gemfile: gemfiles/rails_edge.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
  - gemfile: gemfiles/rails_edge.gemfile

script: bundle exec rake test

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
