language: ruby
rvm:
  - 2.3.1
  - 2.5.1

matrix:
  allow_failures:
    - rvm: 2.5.1

script: bundle exec rake test

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
